import type { Game, LibraryEntry, Player, RatingStats, Review } from "./types";

export const sampleGames: Game[] = [
  {
    id: "outer-wilds",
    slug: "outer-wilds",
    title: "Outer Wilds",
    summary:
      "A solar system stuck in a 22-minute loop that ends when the sun explodes. Every run you keep only what you learned.",
    releaseDate: "2019-05-28",
    developers: ["Mobius Digital"],
    genres: ["Adventure", "Puzzle"],
    platforms: ["PC", "PS5", "Xbox Series", "Switch"],
    coverUrl: null,
  },
  {
    id: "hollow-knight",
    slug: "hollow-knight",
    title: "Hollow Knight",
    summary:
      "A small knight descends into a ruined insect kingdom full of old secrets, sharp bosses and maps you have to buy.",
    releaseDate: "2017-02-24",
    developers: ["Team Cherry"],
    genres: ["Platform", "Adventure"],
    platforms: ["PC", "PS4", "Xbox One", "Switch"],
    coverUrl: null,
  },
  {
    id: "celeste",
    slug: "celeste",
    title: "Celeste",
    summary:
      "Madeline climbs a mountain that pushes back. Tight jumps, a thousand retries and a story about anxiety that lands.",
    releaseDate: "2018-01-25",
    developers: ["Maddy Makes Games"],
    genres: ["Platform", "Indie"],
    platforms: ["PC", "PS4", "Xbox One", "Switch"],
    coverUrl: null,
  },
  {
    id: "hades",
    slug: "hades--1",
    title: "Hades",
    summary:
      "The son of the god of the dead fights his way out of the underworld, one failed escape and one family argument at a time.",
    releaseDate: "2020-09-17",
    developers: ["Supergiant Games"],
    genres: ["Action", "Roguelike"],
    platforms: ["PC", "PS5", "Xbox Series", "Switch"],
    coverUrl: null,
  },
  {
    id: "disco-elysium",
    slug: "disco-elysium",
    title: "Disco Elysium",
    summary:
      "A detective wakes up with no memory and a murder to solve, arguing with the voices of his own skills along the way.",
    releaseDate: "2019-10-15",
    developers: ["ZA/UM"],
    genres: ["RPG", "Adventure"],
    platforms: ["PC", "PS5", "Xbox Series", "Switch"],
    coverUrl: null,
  },
  {
    id: "stardew-valley",
    slug: "stardew-valley",
    title: "Stardew Valley",
    summary:
      "Leave the office job, inherit an overgrown farm and slowly become part of a small town that runs on seasons.",
    releaseDate: "2016-02-26",
    developers: ["ConcernedApe"],
    genres: ["Simulation", "RPG"],
    platforms: ["PC", "PS4", "Xbox One", "Switch"],
    coverUrl: null,
  },
  {
    id: "portal-2",
    slug: "portal-2",
    title: "Portal 2",
    summary:
      "Two portals, one sarcastic AI and a crumbling test facility. Physics puzzles with some of the best writing in games.",
    releaseDate: "2011-04-19",
    developers: ["Valve"],
    genres: ["Puzzle"],
    platforms: ["PC", "PS3", "Xbox 360", "Switch"],
    coverUrl: null,
  },
  {
    id: "elden-ring",
    slug: "elden-ring",
    title: "Elden Ring",
    summary:
      "An open world of broken kingdoms and very large bosses. Get lost, get flattened, come back stronger.",
    releaseDate: "2022-02-25",
    developers: ["FromSoftware"],
    genres: ["Action", "RPG"],
    platforms: ["PC", "PS5", "Xbox Series"],
    coverUrl: null,
  },
  {
    id: "return-of-the-obra-dinn",
    slug: "return-of-the-obra-dinn",
    title: "Return of the Obra Dinn",
    summary:
      "A ghost ship drifts back into port with its crew missing. Work out who died, how, and who is lying in the logbook.",
    releaseDate: "2018-10-18",
    developers: ["Lucas Pope"],
    genres: ["Puzzle", "Adventure"],
    platforms: ["PC", "PS4", "Xbox One", "Switch"],
    coverUrl: null,
  },
  {
    id: "inscryption",
    slug: "inscryption",
    title: "Inscryption",
    summary:
      "A card game played in a dark cabin against someone you cannot quite see, and it keeps turning into something else.",
    releaseDate: "2021-10-19",
    developers: ["Daniel Mullins Games"],
    genres: ["Card", "Roguelike"],
    platforms: ["PC", "PS5", "Xbox Series", "Switch"],
    coverUrl: null,
  },
  {
    id: "tunic",
    slug: "tunic",
    title: "Tunic",
    summary:
      "A small fox explores a world whose instruction manual is scattered across it, written in a language you cannot read.",
    releaseDate: "2022-03-16",
    developers: ["TUNIC Team"],
    genres: ["Action", "Adventure"],
    platforms: ["PC", "PS5", "Xbox Series", "Switch"],
    coverUrl: null,
  },
  {
    id: "balatro",
    slug: "balatro",
    title: "Balatro",
    summary:
      "Poker hands, silly jokers and multipliers that get out of hand. One more run turns into three hours.",
    releaseDate: "2024-02-20",
    developers: ["LocalThunk"],
    genres: ["Card", "Roguelike"],
    platforms: ["PC", "PS5", "Xbox Series", "Switch"],
    coverUrl: null,
  },
];

export const sampleRatingStats: Record<string, RatingStats> = {
  "outer-wilds": { average: 4.4, count: 18204, distribution: [310, 402, 1480, 5220, 10792] },
  "hollow-knight": { average: 4.3, count: 22931, distribution: [420, 690, 2410, 7880, 11531] },
  celeste: { average: 4.2, count: 15377, distribution: [260, 540, 2130, 5910, 6537] },
  "hades--1": { average: 4.4, count: 18400, distribution: [180, 350, 1620, 6400, 9850] },
  "disco-elysium": { average: 4.3, count: 12600, distribution: [240, 380, 1310, 3900, 6770] },
  "stardew-valley": { average: 4.3, count: 24000, distribution: [150, 420, 2600, 9100, 11730] },
  "portal-2": { average: 4.6, count: 26000, distribution: [120, 260, 1400, 7300, 16920] },
  "elden-ring": { average: 4.3, count: 29000, distribution: [520, 880, 3100, 9800, 14700] },
  "return-of-the-obra-dinn": { average: 4.4, count: 8000, distribution: [90, 210, 820, 2600, 4280] },
  inscryption: { average: 4.0, count: 11000, distribution: [210, 460, 1900, 4700, 3730] },
  tunic: { average: 3.9, count: 8000, distribution: [170, 390, 1640, 3500, 2300] },
  balatro: { average: 4.2, count: 17000, distribution: [260, 520, 2100, 6200, 7920] },
};

export const sampleReviews: Review[] = [
  {
    id: "r1",
    gameId: "outer-wilds",
    author: { username: "mara_plays" },
    rating: 5,
    body: "The only game I wish I could forget so I could play it for the first time again. Twenty-two minutes has never felt this big.",
    platform: "PC",
    hoursPlayed: 31,
    likes: 1214,
    createdAt: "2026-03-02",
  },
  {
    id: "r2",
    gameId: "outer-wilds",
    author: { username: "okan.dev" },
    rating: 4,
    body: "Half of it is reading ship logs, and somehow that half is the best part. The controls fought me for the first two hours.",
    platform: "Switch",
    hoursPlayed: 18,
    likes: 386,
    createdAt: "2026-05-19",
  },
  {
    id: "r3",
    gameId: "outer-wilds",
    author: { username: "quietlobby" },
    rating: 4.5,
    body: "Went in blind, wrote notes on paper like it was 1996. The ending made me sit in silence for a while.",
    platform: "PS5",
    hoursPlayed: 24,
    likes: 201,
    createdAt: "2026-07-08",
  },
  {
    id: "r4",
    gameId: "outer-wilds",
    author: { username: "deniz_k" },
    rating: 3,
    body: "Brilliant idea, but the anglerfish section almost made me quit. Worth pushing through, barely.",
    platform: "PC",
    hoursPlayed: 15,
    likes: 94,
    createdAt: "2026-08-21",
  },
  {
    id: "r5",
    gameId: "hollow-knight",
    author: { username: "mara_plays" },
    rating: 5,
    body: "Every corner of the map hides something. I got lost for hours and loved being lost.",
    platform: "Switch",
    hoursPlayed: 52,
    likes: 640,
    createdAt: "2026-01-14",
  },
  {
    id: "r6",
    gameId: "celeste",
    author: { username: "okan.dev" },
    rating: 4.5,
    body: "Died 2,400 times and never once felt it was unfair. The B-sides are a different story.",
    platform: "PC",
    hoursPlayed: 20,
    likes: 312,
    createdAt: "2026-04-03",
  },
];

export const samplePlayers: Player[] = [
  {
    username: "mara_plays",
    bio: "Mostly indies, always with a notebook. Will replay anything with a good map.",
    joinedAt: "2025-02-11",
  },
  {
    username: "okan.dev",
    bio: "Plays on the train, reviews on the way back.",
    joinedAt: "2025-06-03",
  },
  {
    username: "quietlobby",
    bio: "Puzzle games and long silences.",
    joinedAt: "2025-11-20",
  },
  {
    username: "deniz_k",
    bio: "Honest scores, no hype.",
    joinedAt: "2026-01-08",
  },
];

export const sampleLibrary: LibraryEntry[] = [
  { username: "mara_plays", gameId: "outer-wilds", status: "played", rating: 5, updatedAt: "2026-03-02" },
  { username: "mara_plays", gameId: "hollow-knight", status: "played", rating: 5, updatedAt: "2026-01-14" },
  { username: "mara_plays", gameId: "hades", status: "played", rating: 4.5, updatedAt: "2026-04-22" },
  { username: "mara_plays", gameId: "portal-2", status: "played", rating: 5, updatedAt: "2025-09-30" },
  { username: "mara_plays", gameId: "disco-elysium", status: "played", rating: 4, updatedAt: "2025-12-05" },
  { username: "mara_plays", gameId: "celeste", status: "played", rating: 4, updatedAt: "2025-08-17" },
  { username: "mara_plays", gameId: "elden-ring", status: "playing", rating: null, updatedAt: "2026-08-30" },
  { username: "mara_plays", gameId: "tunic", status: "backlog", rating: null, updatedAt: "2026-07-12" },
  { username: "mara_plays", gameId: "return-of-the-obra-dinn", status: "backlog", rating: null, updatedAt: "2026-06-01" },
  { username: "mara_plays", gameId: "balatro", status: "backlog", rating: null, updatedAt: "2026-05-15" },
  { username: "okan.dev", gameId: "outer-wilds", status: "played", rating: 4, updatedAt: "2026-05-19" },
  { username: "okan.dev", gameId: "celeste", status: "played", rating: 4.5, updatedAt: "2026-04-03" },
  { username: "okan.dev", gameId: "stardew-valley", status: "played", rating: 3.5, updatedAt: "2025-10-11" },
  { username: "okan.dev", gameId: "inscryption", status: "played", rating: 4, updatedAt: "2026-02-27" },
  { username: "okan.dev", gameId: "balatro", status: "playing", rating: null, updatedAt: "2026-09-01" },
  { username: "okan.dev", gameId: "hades", status: "backlog", rating: null, updatedAt: "2026-06-18" },
  { username: "okan.dev", gameId: "disco-elysium", status: "backlog", rating: null, updatedAt: "2026-03-09" },
  { username: "quietlobby", gameId: "outer-wilds", status: "played", rating: 4.5, updatedAt: "2026-07-08" },
  { username: "quietlobby", gameId: "return-of-the-obra-dinn", status: "played", rating: 5, updatedAt: "2026-02-14" },
  { username: "quietlobby", gameId: "tunic", status: "playing", rating: null, updatedAt: "2026-08-25" },
  { username: "deniz_k", gameId: "outer-wilds", status: "played", rating: 3, updatedAt: "2026-08-21" },
  { username: "deniz_k", gameId: "elden-ring", status: "played", rating: 4, updatedAt: "2026-05-02" },
  { username: "deniz_k", gameId: "celeste", status: "backlog", rating: null, updatedAt: "2026-07-30" },
];
